[build]
    TZ = "America/Denver"
    publish = "dist/"
    command = "npm run prod"

[context.production.environment]
    ELEVENTY_ENV = "production"

[context.deploy-preview.environment]
    ELEVENTY_ENV = "staging"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  prettyURLs = true
  # Append missing trailing slash to pretty URL
  trailingSlash = true